### ISSUE TITLE
Change text logo to Image

### ISSUE THREAD

**Issue by ViktorJoseph** [ViktorJoseph/judahsrecords.github.io#3]
Change text logo to Image

find logo file here: https://drive.google.com/file/d/19ScaYZUgSglsq-F1_oo3ubR2HL7gb81u/view?usp=sharing

**Comment by jeremiey** [comment]
On it sir

**Comment by jeremiey** [comment]
Okay sir
I'll apply that.

**Comment by jeremiey** [comment]
In the booking session form, I changed the US States dropdown to a Nigerian States dropdown.
